### ISSUE TITLE
onAdAction callback always invoked with action_type: CLICKED

### ISSUE THREAD

**Issue by iPruch** [sdkbox/sdkbox-sample-admob#1]
Hello. In my game project I use **SDKBOX Ads** plugin with AdMob, AdColony and Chartboost for now. I've implemented the `PluginSDKboxAds` callbacks in my game class, and I've noticed that on showing an **AdMob** interstitial ad, the `onAdAction` callback always gets called with `action_type CLICKED`, but I didn't click on the ad. This doesn't happen with AdColony nor with Chartboost.

So I decided to try with sdkbox sample projects, with same results:

```
08-24 17:49:49.637 30645 30679 D SdkboxAds: PluginSdkboxAds onAdAction: unit:'AdMob' zone:'gameover' action:'CLICKED' extras:'false'
08-24 17:49:49.644 30645 30679 D cocos2d-x debug info: onAdAction, ad_unit_id: AdMob, zone_location_place_you_name_it: gameover, action_type: CLICKED
```

Why is this happening? I'm doing custom actions on my game in the `onAdAction` callback, but if I get a fake CLICKED callback, then it's going to behave wrongly.

Thank you

**Comment by yinjimmy** [comment]
Let's check it.

**Comment by yinjimmy** [comment]
OK, I got the code.

**Comment by yinjimmy** [comment]
Will release soon, thanks again.

**Comment by iPruch** [comment]
> Let's check it. Andorid or iOS ?

Oh, I'm sorry for not responding. I didn't receive the notification of GitHub. I imagine you've figured it out already, but it happened on both Android and iOS.

> Will release soon, thanks again.

Thank you for the quick answering, bug fixing and support! You're very active both here on GitHub and on the Cocos2d-x forum!
